### ISSUE TITLE
Cannot execute CacTool, missing Main module

### ISSUE THREAD

**Issue by giovsta** [cactool/cactool#75]
After correctly installing the package and its requirements I cannot run it. As I execute cactool in the command prompt it gives me the error: can't find '__main__' module in 'cactool'

I understand the problem may be my superficial knowledge of python, but please let me know how I can solve it.

**Comment by leelum** [comment]
Thanks for highlighting this issue: What platform are you using, Windows? We'll try and fix this ASAP

**Comment by giovsta** [comment]
Yes, Windows 10, I am installing the package in my laptop, not in Anaconda.

**Comment by polisci-quant-nerd** [comment]
I cannot run cactool either. I’m using a Mac Monterey with python 3.8. After pip installed, I try to run cactool via command line and then I get the  error Connection in use: ('', 8000).

**Comment by leelum** [comment]
> Yes, Windows 10, I am installing the package in my laptop, not in Anaconda.

This *should* be fixed @giovsta.  If you update to the latest with the below:

`pip install cactool --upgrade`

Then run Cactool with the -m operator as below:
`python3 -m cactool` or 'python -m cactool'

It should work!
