### ISSUE TITLE
Cannot delete uploaded dataset 

### ISSUE THREAD

**Issue by polisci-quant-nerd** [cactool/cactool#78]
Hi,

After registration and setting up a project, I uploaded a trial dataset to be coded. When I try to delete the trial one (I clicked edit and then scroll down to delete the data), I ended up with a webpage (http://0.0.0.0:8000/dataset/delete/) saying "Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again." Is it due to some server error on your end? I tried several times, always got the same message. 

Thanks!

**Comment by dignissimus** [comment]
Hey! This should be fixed now.

You can update to 0.5.7.6 by updating with `pip install -U cactool`. After this, does it work on your end?
